### ISSUE TITLE
Invalid IP address displays on FUI title and on Dashboard

### ISSUE THREAD

**Issue by elwray** [ultranetorg/uc#13]
## Description

Invalid IP address displays on FUI title and on Dashboard.

## Correct behavior

Correct public IP (?) / local IP (?) should be displayed.

## Steps to reproduce

1. Start FUI app.
2. Open Dashboard.
3. Observe title and "IP:Port" value on Dashboard.

## Screenshots

![image](https://user-images.githubusercontent.com/5120173/149770035-9763569a-e1f2-4367-b053-14a03d68dbc0.png)

## Software settings and version

Version: 0.0.143.0
Network: Test0

**Comment by ultranetorg** [comment]
this is not IP from settings this one is an external IP which is detected after any connection is established

**Comment by ultranetorg** [comment]
UI improved
