### ISSUE TITLE
Unable to gen balance

### ISSUE THREAD

**Issue by elwray** [ultranetorg/uc#15]
## Description

Unable to get balance.

## Correct behavior

Balance should be received / shown.

## Steps to reproduce

1. You should have one or more accounts.
2. Launch app.
3. Go to Accounts.

## Screenshots

![image](https://user-images.githubusercontent.com/5120173/150578968-2f023c52-9bc1-4ef8-9f02-741fabc25958.png)

## Software settings and version

Version: 0.0.144.0
Network: Test0

**Comment by ultranetorg** [comment]
Fixed
