### ISSUE TITLE
Unable to connect to network

### ISSUE THREAD

**Issue by elwray** [ultranetorg/uc#3]
## Description

Unable to connect to network.

## Correct behavior

Local node should be connected to Ultranet network.

## Steps to reproduce

1. Launch FUI app.
2. Open Peers.
3. Observe table.
4. Local node not connected to any remote node.

## Screenshots

![image](https://user-images.githubusercontent.com/5120173/149485233-6682ca70-99bf-493f-9922-430edd5675bc.png)

## Software settings and version

Version: 0.0.143.0
Network: Test0

**Comment by ultranetorg** [comment]
Unable to reproduce, check firewall settings
